### ISSUE TITLE
gen8_post_processing: optimization for gen8_pp_object_walker

### ISSUE THREAD

**Issue by nelsoncs-intel** [intel/intel-vaapi-driver#252]
gen8_pp_object_walker makes an unnecessary function call, checks a
return value that is always zero and makes non-indexed variable
assignments.  All of which occurs inside nested for loops.

Move non-indexed assignments outside the iterative block and inline the
rest. This decreases frame drops for saturating workloads.

[0001-gen8_post_processing-optimization-for-gen8_pp_object.txt](https://github.com/01org/intel-vaapi-driver/files/1235136/0001-gen8_post_processing-optimization-for-gen8_pp_object.txt)

**Comment by chivakker** [comment]
@nelsoncs-intel can you please submit the patch as a pull request?
