### ISSUE TITLE
skylake platform decode hevc - 4800x3840 picture falied

### ISSUE THREAD

**Issue by jinlongzhou** [intel/intel-vaapi-driver#390]
my vaapi version is 1.8.0   intel-vaapi-driver version is 1.8.0,  i wonder wether the version of vaapi and vaapi driver  supports the hevc video (size over 4k) decoding ?

**Comment by xhaihao** [comment]
No, the driver doesn't support size over 4k.

**Comment by jinlongzhou** [comment]
dafsd
