### ISSUE TITLE
iHD_drv_video.so has no function __vaDriverInit_1_0

### ISSUE THREAD

**Issue by djmv** [intel/intel-vaapi-driver#406]
I built and installed intel-vaapi-driver and Intel libva but I got this error with vainfo.  

My computer: 
model name: Intel® Core™ i7-4770 CPU @ 3.40GHz

vainfo 
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva error: /usr/local/lib/dri/iHD_drv_video.so has no function __vaDriverInit_1_0
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

**Comment by chivakker** [comment]
did you compile libva-utils against libva?

**Comment by chivakker** [comment]
btw, iHD_drv_video.so lives here: www.github.com/intel/media-driver

LIBVA_DRIVER_NAME=iHD vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open <redacted>/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.1.pre1)
vainfo: Driver version: Intel iHD driver - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD

**Comment by djmv** [comment]
Yes I compiled libva-utils too. When  $ ./autogen.sh 
![image](https://user-images.githubusercontent.com/19581489/43217447-4a910408-9007-11e8-9cde-ad08c6bfe946.png)

but still not work. When consult vainfo 
![image](https://user-images.githubusercontent.com/19581489/43217623-bf105004-9007-11e8-970f-a061410d47db.png)

**Comment by chivakker** [comment]
Did you compile iHD_drv_video driver after updating libva? In any case this question should go to media-driver project.

**Comment by djmv** [comment]
Yes, I compiled  iHD_drv_video after updating libva.  Thanks !

**Comment by xhaihao** [comment]
Please file iHD issue at https://github.com/intel/media-driver

**Comment by liv09370** [comment]
Cause i7 4770 not supported.
