### ISSUE TITLE
meson build fails with 2.2.0 release

### ISSUE THREAD

**Issue by rezso** [intel/intel-vaapi-driver#411]
When I try to compile the 2.2.0 with meson, it fails with this error:
src/meson.build:7:11: ERROR:  Unknown variable "intel_vaapi_driver_pre_version".
In addition, the INTEL_DRIVER_PRE_VERSION will be undefined in src/meson.build, which causes another error during build.

**Comment by ceyusa** [comment]
It seems that commit 1eddac3 forgot to add a cero at the end of the version string:

https://github.com/intel/intel-vaapi-driver/commit/1eddac3e38658169dafd7c0767c2fa34de68d388#diff-969b60ad3d206fd45c208e266ccfed38L3

**Comment by xhaihao** [comment]
fixed in https://github.com/intel/intel-vaapi-driver/pull/412
