### ISSUE TITLE
i915/kbl: GPU HANG: ecode 9:2:0xa8dfbffd, in VideoPlayer [770], reason: hang on vcs0, action: reset

### ISSUE THREAD

**Issue by mlauss** [intel/intel-vaapi-driver#425]
2160p HEVC video, played on a 1080 output.  One frame of the video is displayed, then the vcs0 hang occurs.  using latest -git versions of libva and intel-vaapi-driver.
Attached the gpu crash dump.
[kblcrash.txt](https://github.com/intel/intel-vaapi-driver/files/2644024/kblcrash.txt)

**Comment by xhaihao** [comment]
Which video player are you running? if possible, could you share your video sample?

**Comment by mlauss** [comment]
Video Player is Kodi (XBMC), latest git snapshot.  I've extracted a 10 second sample (~64MB), do you have a location I can upload it to?

**Comment by xhaihao** [comment]
Are you able to reproduce this issue with other players, such as mpv? Sorry I haven't a location for uploading. If possible, you may upload your video sample to a free cloud storage, then share the link.

**Comment by mlauss** [comment]
Hm, I've tried with a recent git snapshot of mpv,  "mpv --hwdec=vaapi --vo=vaapi brokenfile.mkv" and it plays it just fine.   I'm closing this one, is probably an issue with the player in kodi/xbmc.
