### ISSUE TITLE
intel_gpu_top error on  Intel(R) Celeron(R) G4900 

### ISSUE THREAD

**Issue by waiter89** [intel/intel-vaapi-driver#433]
root@150,>>> intel_gpu_top 
Test requirement not met in function drm_open_driver, file drmtest.c:359:
Test requirement: !(fd<0)
No known gpu found
Last errno: 2, No such file or directory
SKIP (-1.000s) 

root@150,>>> lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:3e0f] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:3e93]
00:12.0 Signal processing controller [1180]: Intel Corporation Device [8086:a379] (rev 10)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:a36d] (rev 10)
00:14.2 RAM memory [0500]: Intel Corporation Device [8086:a36f] (rev 10)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:a360] (rev 10)
00:17.0 SATA controller [0106]: Intel Corporation Device [8086:a352] (rev 10)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:a33c] (rev f0)
00:1c.7 PCI bridge [0604]: Intel Corporation Device [8086:a33f] (rev f0)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:a303] (rev 10)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:a348] (rev 10)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:a323] (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device [8086:a324] (rev 10)
01:00.0 PCI bridge [0604]: Integrated Technology Express, Inc. Device [1283:8892] (rev 71)
03:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 16)

**Comment by xhaihao** [comment]
This is not an issue of intel-vaapi-driver, please file bug to https://gitlab.freedesktop.org/drm/igt-gpu-tools
