### ISSUE TITLE
vainfo init fail

### ISSUE THREAD

**Issue by waiter89** [intel/intel-vaapi-driver#435]
surveil@localhost:/usr/lib64/dri> DISPLAY=:0.0 vainfo
error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 1.3.0
libva info: va_getDriverName() returns -1
libva info: User requested driver 'i965'
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_3
g_intel_debug_option_flags:1
vainfo: intel_driver.c:113: intel_driver_init: Assertion `((((struct drm_state *)(ctx)->drm_state)->auth_type == (VA_DRM_AUTH_DRI1)) || (((struct drm_state *)(ctx)->drm_state)->auth_type == (VA_DRM_AUTH_DRI2)) || (((struct drm_state *)(ctx)->drm_state)->auth_type == (VA_DRM_AUTH_CUSTOM)))' failed.
Aborted (core dumped)

localhost:/usr/lib64/dri # lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:3e0f] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:3e93]
00:12.0 Signal processing controller [1180]: Intel Corporation Device [8086:a379] (rev 10)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:a36d] (rev 10)
00:14.2 RAM memory [0500]: Intel Corporation Device [8086:a36f] (rev 10)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:a360] (rev 10)
00:17.0 SATA controller [0106]: Intel Corporation Device [8086:a352] (rev 10)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:a33c] (rev f0)
00:1c.7 PCI bridge [0604]: Intel Corporation Device [8086:a33f] (rev f0)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:a303] (rev 10)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:a348] (rev 10)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:a323] (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device [8086:a324] (rev 10)
01:00.0 PCI bridge [0604]: Integrated Technology Express, Inc. Device [1283:8892] (rev 71)
03:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 16)

**Comment by waiter89** [comment]
升级操作系统后,vainfo正常

**Comment by xhaihao** [comment]
The issue was resolved after upgrading the system.
