### ISSUE TITLE
New Release for libva + wayland

### ISSUE THREAD

**Issue by colemickens** [intel/intel-vaapi-driver#449]
Can we please get a new stable release?

As of right now, Intel + libva (+ Wayland?) is just broken on up-to-date distros.

see: #419

**Comment by mattst88** [comment]
Haihao: please make a new release with the fix for #419

**Comment by mattst88** [comment]
Ping! Make a release so distributions can ship something that works.

**Comment by tjaalton** [comment]
Ubuntu would like to have this as well

/me speaking as the X/Mesa etc maintainer at Canonical

**Comment by mattst88** [comment]
Please close this issue now that a release has been made.
