### ISSUE TITLE
Support Ice Lake architecture

### ISSUE THREAD

**Issue by EwoutH** [intel/intel-vaapi-driver#469]
Intel [formally announced](https://newsroom.intel.com/news-releases/2019-computex-intel-disclosures/) their 10th Gen processors today, based on the Ice Lake (ICL) micro-architecture. It would be nice if support for their new media encoder could be added.

The [Intel Media Driver](https://github.com/intel/media-driver) already supports Ice Lake, maybe code from that repo could be recycled.

**Comment by mathstuf** [comment]
Does this include Comet Lake? Or should I open another issue?

**Comment by uartie** [comment]
There are no plans to add support for additional hardware in this driver.  Please use the https://github.com/intel/media-driver (iHD) for all platforms after CFL.
