### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/intel-vaapi-driver#478]
https://github.com/intel/intel-vaapi-driver/blob/e60af2163cc47d1820cf4b22b71321e3c2b0c9f2/src/gen75_vme.c#L518

for loop lacks the third conditional expression， can make endless loop

**Comment by tmm1** [comment]
How can it  be endless?


https://github.com/intel/intel-vaapi-driver/blob/e60af2163cc47d1820cf4b22b71321e3c2b0c9f2/src/gen75_vme.c#L563
