### ISSUE TITLE
Support Comet Lake architecture

### ISSUE THREAD

**Issue by nielsdg** [intel/intel-vaapi-driver#499]
Analogous to #469, we would like to have VA-API support for Comet Lake devices if possible, esp. wrt to media decoding.

**Comment by mathstuf** [comment]
I started doing something along these lines after my comment in #469, but it probably involves having hardware spec sheets to actually get right. I suspect too much blind poking is liable to cause kernel lockups or other nasty effects :) .

**Comment by uartie** [comment]
There are no plans to add support for additional hardware in this driver.  Please use the https://github.com/intel/media-driver (iHD) for all platforms after CFL.
