### ISSUE TITLE
vaGetImage() doesn't fill the last column and row in chroma plane if the dimension is odd

### ISSUE THREAD

**Issue by rosetta-jpn** [intel/intel-vaapi-driver#516]
The title describes the issue.
I found this bug when I map an odd dimension frame (e.g. 321x241) with VA Image by vaCreateImage() and vaGetImage().
In this case, chroma plane size is 161x121. vaCreateImage() allocates so, but I suspect vaGetImage() fills up to 160x120.
If I change the part of code to vaDeriveImage(), the issue was gone.

**Comment by sreerenjb** [comment]
Any Sample code to share? Is there a corresponding chromeos bug open somewhere?
@xhaihao  ping

**Comment by sreerenjb** [comment]
Reproducible with gst:
gst-launch-1.0 -v videotestsrc ! videoscale ! video/x-raw, width=321, height=241 ! vaapipostproc ! xvimagesink

**Comment by xhaihao** [comment]
@sreerenjb @rosetta-jpn Could you give a try with https://github.com/xhaihao/intel-vaapi-driver/tree/fix-odd-resolution on your side? It works on my SKL.

**Comment by sreerenjb** [comment]
@xhaihao 
Yup, it is fixing the GStreamer pipeline for sure. Tested on KBL.

**Comment by sreerenjb** [comment]
Thank you Haihao

**Comment by sreerenjb** [comment]
@xhaihao HIro confirmed that it fixed the chrome issue too.
Can you please merge the fix?

**Comment by rosetta-jpn** [comment]
Haihao, gentle ping.

**Comment by xhaihao** [comment]
@sreerenjb @rosetta-jpn Thanks for testing the patch, I will submit a PR ASAP.
