### ISSUE TITLE
i965_drv_video.so init failed

### ISSUE THREAD

**Issue by quiricada** [intel/intel-vaapi-driver#518]
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib64/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

[stracevainfo.txt](https://github.com/intel/intel-vaapi-driver/files/5092122/stracevainfo.txt)

Linux lenovox1 5.8.1 #1 SMP Tue Aug 18 17:32:47 PST 2020 x86_64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz GenuineIntel GNU/Linux

**Comment by xhaihao** [comment]
the legacy i965 driver doesn't support your HW, please use https://github.com/intel/media-driver instead.
