### ISSUE TITLE
does this driver could used in tiggerlake ?

### ISSUE THREAD

**Issue by sharewzy** [intel/intel-vaapi-driver#531]
is this driver still be used?i want to use this in the tiggerlake platform for 4k&8k decoder,does this driver support?

**Comment by uartie** [comment]
No, this driver does not support Tiger Lake.  See https://github.com/intel/intel-vaapi-driver/blob/master/README for list of supported platforms.  For Tiger Lake, please use https://github.com/intel/media-driver.
