### ISSUE TITLE
Crocus driver ?

### ISSUE THREAD

**Issue by thetick1234567890** [intel/intel-vaapi-driver#533]
Are there plans for a crocus vaapi driver ?  When I switch mesa to crocus driver I get an error with vainfo that states  crocus_drv_video.so is not found.  As a workaround if make a symbolic link : "sudo ln -s i965_drv_video.so crocus_drv_video.so" hardware acceleration works fine as the existing i965 driver is used.

**Comment by lorn10** [comment]
I can confirm this problem for an Intel Sandy Bridge based system. The VAAPI support is currently missing when the new Gallium 3D Crocus driver is used.

However, there is a comment at phoronix forums from an Intel developer which notes that "Media support would certainly be neat" But it seems somewhat unclear when this will happen. So as for now, we only can wait and hope that this will happen sometimes in the near future. Source: [Mesa's New "Crocus" OpenGL Driver Is Performing Well For Old Intel Hardware](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/1262210-mesa-s-new-crocus-opengl-driver-is-performing-well-for-old-intel-hardware/page2)

**Comment by jbeich** [comment]
Can you reproduce with libva from `master` branch? If not close the issue.

**Comment by lorn10** [comment]
This doesn't land in Mesa, right? I am on `Mesa 22.0.0-devel (git-b5848b2 2021-11-27 focal-oibaf-ppa)` and I still get an error message when a h264 video is played via mpv and crocus is in use.

Maybe @thetick1234567890 is able to build `libva` from `master` an try this out.

**Comment by thetick1234567890** [comment]
Thanks! Can you please release a new official package as I'm hoping this gets in the 22.04 Ubuntu release.
